### ISSUE TITLE
Parse error: syntax error

### ISSUE THREAD

**Issue by haomaiyys** [springjk/wordpress-wechat-broadcast#2]
Parse error: syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in /data/home/qxu1192420262/htdocs/wp-content/plugins/wechat-broadcast/wechat-broadcast.php on line 12

**Comment by springjk** [comment]
感谢你的反馈，对于这个问题我认为是你的 PHP 版本 < 5.3， Namespace 的支持在 5.3 之后，详见 [PHP 5.3.0 Release Announcement](http://php.net/namespaces)，如果无法确认请留下你的联系方式。
