### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by lszrooney** [springjk/wordpress-wechat-broadcast#4]
When I Install this Plugin,the following problem occured

Parse error: syntax error, unexpected '[', expecting ')' in /home/boycookc/domains/lanerzhao.com/public_html/wp-content/plugins/wechat-brodercast/vendor/guzzlehttp/promises/src/functions.php on line 41

**Comment by springjk** [comment]
Hi, friend, i think that problem is your PHP version is too old, make sure your PHP version is 5.6+.
