### ISSUE TITLE
how to fix 推送微信失败 : api unauthorized hint: [Jw1Gja0655vr31!]

### ISSUE THREAD

**Issue by sanhung** [springjk/wordpress-wechat-broadcast#6]
how to fix 推送微信失败 : api unauthorized hint: [Jw1Gja0655vr31!]  ????

**Comment by springjk** [comment]
api unauthorized hint；你的账号没有权限啊，没有群发权限啊，公众号认证（300 RMB）了吗？详见 http://mp.weixin.qq.com/wiki/15/40b6865b893947b764e2de8e4a1fb55f.html
